### ISSUE TITLE
Doesn't collapse brackets with links

### ISSUE THREAD

**Issue by gatezh** [mrv1k/bracketless#7]
Page example [https://en.wikipedia.org/wiki/Google](https://en.wikipedia.org/wiki/Google)

Doesn't collapse brackets with links inside:
- (Google Maps/Waze/Earth/Street View)
- (Singapore, Hong Kong and Taiwan) etc.

**Comment by mrv1k** [comment]
That's actually by design. I think that collapsing brackets with links would be confusing

Here is the the line that's responsible for that: https://github.com/mrv1k/bracketless/blob/master/core/src/bracketless.js#L66

I decided to not indicate that at how to page. Do you think I should mention it there?

**Comment by mrv1k** [comment]
Just testing stuff.
